version: '3.8'

services:
  rest:
    build: 
      context: .
    depends_on:
      - db
    container_name: rest
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    command: sh -c "npm run start:dev"

  db:
    image: postgres:alpine3.15
    container_name: postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdb:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network
volumes:
  app:
  pgdb:
networks:
  app-network:
    name: custom-network
    driver: bridge